### ISSUE TITLE
Readme unclear

### ISSUE THREAD

**Issue by noahsb** [11ty/eleventy-base-blog#91]
In the _Implementation Notes_ section of the `README`, it states:

> Because `css` and `png` are listed in `templateFormats` but are not supported template types, any files with these extensions will be copied without modification to the output (while keeping the same directory structure).

However, taking a look at `.eleventy.js`, the `templateFormats` are (`css` and `png` are not listed):

```
"md",
"njk",
"html",
"liquid"
```

Personally, this led to some confusion and I think some rewording would be helpful here. I think the point we'd like to get across is this:

> If you list file extensions within `templateFormats` that are unsupported template types (such as `css` and `png`), any file with these extensions will be copied without modification to the output (while keeping the same directory structure).

If the above is true, and you're okay with that change, I'd love to submit a PR to make that modification. Thanks!!

**Comment by zachleat** [comment]
There have been a few changes to that section of the README, appreciate the ping! It needed some cleanup.

As a follow up it might be helpful to read through some of the commentary on https://github.com/11ty/eleventy/issues/746

Personally, I’d rather folks use the `addPassthroughCopy` configuration API exclusively rather than the templateFormats passthrough copy
